<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Configurations>Debug;Release;Debug|AnyCPU;Release|x64</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ComputerAskeyboardLinux32\ComputerAsKeyboardInterface.csproj" />
    </ItemGroup>

</Project>
